# SPDX-FileCopyrightText: © 2024 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[version]
source = "vcs"

[metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
    { path = "README.md" },
]

[[metadata.hooks.fancy-pypi-readme.substitutions]]
pattern = "\\[INSTALL.md\\]\\((?!https?://)\\S+?\\)"
replacement = "[INSTALL.md](https://github.com/whiteprints-tests/test-rtd-win32-py311-test/blob/main/INSTALL.md)"

[[metadata.hooks.fancy-pypi-readme.substitutions]]
pattern = "\\[CONTRIBUTING.md\\]\\((?!https?://)\\S+?\\)"
replacement = "[CONTRIBUTING.md](https://github.com/whiteprints-tests/test-rtd-win32-py311-test/blob/main/CONTRIBUTING.md)"

[[metadata.hooks.fancy-pypi-readme.substitutions]]
pattern = "\\[MAINTAINERS.md\\]\\((?!https?://)\\S+?\\)"
replacement = "[MAINTAINERS.md](https://github.com/whiteprints-tests/test-rtd-win32-py311-test/blob/main/MAINTAINERS.md)"

[[metadata.hooks.fancy-pypi-readme.substitutions]]
pattern = "\\]\\(docs/_static/banner.svg\\)\""
replacement = "](https://raw.githubusercontent.com/whiteprints-tests/test-rtd-win32-py311-test/refs/heads/main/docs/_static/banner.svg)"

[build.targets.sdist]
only-include = [
    "src/test_rtd_win32_py311_test",
]

[build.targets.wheel]
packages = [
    "src/test_rtd_win32_py311_test",
]
only-packages = true
artifacts = [
    "**/*.mo",
]
exclude = [
    "**/*.po",
    "**/*.pot",
]

[build.hooks.custom]
dependencies = [
    "babel>=1.25.0",
    "setuptools>=2.16.0",
    "typing-extensions>=4.12.1; python_version<'3.12'",
]
